export enum UsedFor {
  DefaultUsedFor = "DefaultUsedFor",
  Signup = "Signup",
  AffiliateSignup = "AffiliateSignup",
  Signin = "Signin",
  Update = "Update",
  Contact = "Contact",
  SetWithdrawAddress = "SetWithdrawAddress",
  Withdraw = "Withdraw",
  CreateInvitationCode = "CreateInvitationCode",
  SetCommission = "SetCommission",
  SetTransferTargetUser = "SetTransferTargetUser",
  Transfer = "Transfer",
  WithdrawalRequest = "WithdrawalRequest",
  WithdrawalCompleted = "WithdrawalCompleted",
  DepositReceived = "DepositReceived",
  KYCApproved = "KYCApproved",
  KYCRejected = "KYCRejected",
  Announcement = "Announcement",
}

export const UsedFors = [
  UsedFor.Contact,
  UsedFor.SetWithdrawAddress,
  UsedFor.Signin,
  UsedFor.Signup,
  UsedFor.Update,
  UsedFor.Withdraw,
  UsedFor.CreateInvitationCode,
  UsedFor.SetCommission,
  UsedFor.SetTransferTargetUser,
  UsedFor.WithdrawalRequest,
  UsedFor.WithdrawalCompleted,
  UsedFor.DepositReceived,
  UsedFor.KYCApproved,
  UsedFor.KYCRejected,
  UsedFor.Announcement,
]